#!/usr/bin/env python3
"""
Luandro Native Runtime Platform (NRP) — Binding Generator
Phase 10: Binding Generator

Consumes API Specification Language (ASL) YAML files from spec/
and generates:
1. Native C++ headers      -> generated/native/
2. JNI implementations     -> generated/jni/
3. Kotlin wrapper classes  -> generated/kotlin/
4. Luau binding functions  -> generated/luau/
5. Markdown API reference  -> generated/docs/
"""

import os
import sys
import glob
import yaml
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent.parent
SPEC_DIR = ROOT_DIR / "spec"
OUT_NATIVE = ROOT_DIR / "generated" / "native"
OUT_JNI = ROOT_DIR / "generated" / "jni"
OUT_KOTLIN = ROOT_DIR / "generated" / "kotlin"
OUT_LUAU = ROOT_DIR / "generated" / "luau"
OUT_DOCS = ROOT_DIR / "generated" / "docs"

AUTO_GEN_HEADER = """// ============================================================================
// WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY THE NRP BINDING GENERATOR.
// DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN.
// ============================================================================
"""

AUTO_GEN_KOTLIN_HEADER = """// ============================================================================
// WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY THE NRP BINDING GENERATOR.
// DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN.
// ============================================================================
"""

AUTO_GEN_DOC_HEADER = """<!-- ============================================================================ -->
<!-- WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY THE NRP BINDING GENERATOR. -->
<!-- DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN. -->
<!-- ============================================================================ -->
"""

def sanitize_jni_package(package_name):
    return package_name.replace(".", "_")

def map_type_to_kotlin(t):
    t_str = str(t)
    mapping = {
        "String": "String",
        "Boolean": "Boolean",
        "bool": "Boolean",
        "Int": "Int",
        "int": "Int",
        "Long": "Long",
        "long": "Long",
        "Double": "Double",
        "double": "Double",
        "Void": "Unit",
        "void": "Unit",
        "ByteArray": "ByteArray",
        "Handle": "Long"
    }
    return mapping.get(t_str, t_str)

def map_type_to_jni(t):
    t_str = str(t)
    mapping = {
        "String": "jstring",
        "Boolean": "jboolean",
        "bool": "jboolean",
        "Int": "jint",
        "int": "jint",
        "Long": "jlong",
        "long": "jlong",
        "Double": "jdouble",
        "double": "jdouble",
        "Void": "void",
        "void": "void",
        "ByteArray": "jbyteArray",
        "Handle": "jlong"
    }
    return mapping.get(t_str, "jobject")

def generate_native_header(spec):
    cls_name = spec.get("class")
    package = spec.get("package", "")
    module = package.split(".")[-1] if package else "core"
    desc = spec.get("description", "").strip()
    methods = spec.get("methods", []) or []

    out = [AUTO_GEN_HEADER]
    out.append("#pragma once\n")
    out.append("#include <string>")
    out.append("#include <vector>")
    out.append("#include <cstdint>")
    out.append("#include <memory>\n")
    out.append(f"namespace nrp::{module} {{\n")

    if desc:
        formatted_desc = desc.replace('\n', '\n * ')
        out.append(f"/**\n * {formatted_desc}\n */")

    out.append(f"class {cls_name}Gen {{")
    out.append("public:")
    out.append(f"    virtual ~{cls_name}Gen() = default;\n")

    for m in methods:
        m_name = m.get("name")
        ret_type = m.get("return", {}).get("type", "Void") if isinstance(m.get("return"), dict) else "Void"
        args = m.get("args", []) or m.get("parameters", []) or []
        arg_strs = []
        for a in args:
            a_name = a.get("name")
            a_type = a.get("type", "String")
            arg_strs.append(f"const {a_type}& {a_name}")
        params = ", ".join(arg_strs)
        out.append(f"    virtual {ret_type} {m_name}({params}) = 0;")

    out.append("};\n")
    out.append(f"}} // namespace nrp::{module}\n")
    return "\n".join(out)

def generate_jni_impl(spec):
    cls_name = spec.get("class")
    package = spec.get("package", "io.github.luandro")
    module = package.split(".")[-1]
    pkg_jni = sanitize_jni_package(package)
    methods = spec.get("methods", []) or []
    constructors = spec.get("constructors", []) or []

    out = [AUTO_GEN_HEADER]
    out.append("#include <jni.h>")
    out.append("#include <runtime.h>")
    out.append("#include <utilities/jni_utils.h>")
    out.append("#include <string>")
    out.append("#include <vector>\n")
    out.append('extern "C" {\n')

    # Constructors
    for c in constructors:
        jni_fn = c.get("jni_name", f"nativeCreate")
        params = c.get("parameters", []) or []
        jni_params = ["JNIEnv* env", "jclass cls"]
        for p in params:
            p_name = p.get("name")
            p_jni_type = map_type_to_jni(p.get("type", "Long"))
            jni_params.append(f"{p_jni_type} {p_name}")

        out.append(f"JNIEXPORT jlong JNICALL")
        out.append(f"Java_{pkg_jni}_{cls_name}_{jni_fn}({', '.join(jni_params)}) {{")
        out.append("    return nrp::jni::withExceptionTranslation(env, [&]() -> jlong {")
        out.append("        // Native allocation placeholder for generated binding")
        out.append("        return 0L;")
        out.append("    });")
        out.append("}\n")

    # Methods
    for m in methods:
        m_name = m.get("name")
        jni_fn = m.get("jni_name", f"native{m_name[0].upper()}{m_name[1:]}")
        ret_info = m.get("return") or m.get("returns") or {}
        ret_type = ret_info.get("type", "Void") if isinstance(ret_info, dict) else "Void"
        jni_ret = map_type_to_jni(ret_type)

        args = m.get("args", []) or m.get("parameters", []) or []
        jni_params = ["JNIEnv* env", "jobject thiz", "jlong handle"]
        for a in args:
            a_name = a.get("name")
            a_type = map_type_to_jni(a.get("type", "String"))
            jni_params.append(f"{a_type} {a_name}")

        out.append(f"JNIEXPORT {jni_ret} JNICALL")
        out.append(f"Java_{pkg_jni}_{cls_name}_{jni_fn}({', '.join(jni_params)}) {{")
        if jni_ret == "void":
            out.append("    nrp::jni::withExceptionTranslation(env, [&]() {")
            out.append("        // Invocation stub")
            out.append("    });")
        else:
            out.append(f"    return nrp::jni::withExceptionTranslation(env, [&]() -> {jni_ret} {{")
            out.append("        // Invocation stub")
            out.append(f"        return {jni_ret}{{}};")
            out.append("    });")
        out.append("}\n")

    out.append('} // extern "C"\n')
    return "\n".join(out)

def generate_kotlin_wrapper(spec):
    cls_name = spec.get("class")
    package = spec.get("package", "io.github.luandro")
    desc = spec.get("description", "").strip()
    methods = spec.get("methods", []) or []
    constructors = spec.get("constructors", []) or []
    closeable = spec.get("closeable", True)

    out = [AUTO_GEN_KOTLIN_HEADER]
    out.append(f"package {package}\n")
    out.append("import java.io.Closeable")
    out.append("import java.util.concurrent.atomic.AtomicBoolean\n")

    if desc:
        formatted_desc = desc.replace('\n', '\n * ')
        out.append(f"/**\n * {formatted_desc}\n */")

    interface_str = " : Closeable" if closeable else ""
    out.append(f"open class {cls_name}Gen internal constructor(internal val handle: Long){interface_str} {{")
    out.append("    private val isClosed = AtomicBoolean(false)\n")

    has_custom_close_method = False
    for m in methods:
        m_name = m.get("name")
        m_desc = m.get("description", "").strip()
        ret_info = m.get("return") or m.get("returns") or {}
        ret_type_raw = ret_info.get("type", "Void") if isinstance(ret_info, dict) else "Void"
        ret_kt = map_type_to_kotlin(ret_type_raw)
        handle_cls = ret_info.get("handle_class") if isinstance(ret_info, dict) else None

        if handle_cls:
            ret_kt = f"{handle_cls}Gen" if handle_cls != cls_name else f"{cls_name}Gen"
        elif ret_kt in ("Document", "Element", "Elements", "Pattern", "Matcher", "MatchResult", "Runtime", "Context", "JSValue", "Module", "Promise", "LuauVM"):
            ret_kt = f"{ret_kt}Gen"

        args = m.get("args", []) or m.get("parameters", []) or []
        arg_list = []
        jni_arg_list = ["handle"]
        ext_args = ["handle: Long"]
        
        for a in args:
            a_name = a.get("name")
            raw_a_type = a.get("type", "String")
            a_kt_type = map_type_to_kotlin(raw_a_type)

            if a_kt_type in ("Document", "Element", "Elements", "Pattern", "Matcher", "MatchResult", "Runtime", "Context", "JSValue", "Module", "Promise", "LuauVM"):
                arg_list.append(f"{a_name}: {a_kt_type}Gen")
                jni_arg_list.append(f"{a_name}.handle")
                ext_args.append(f"{a_name}: Long")
            elif a_kt_type == "KotlinModule":
                arg_list.append(f"{a_name}: Any")
                jni_arg_list.append(a_name)
                ext_args.append(f"{a_name}: Any")
            else:
                arg_list.append(f"{a_name}: {a_kt_type}")
                jni_arg_list.append(a_name)
                ext_args.append(f"{a_name}: {a_kt_type}")

        jni_fn = m.get("jni_name", f"native{m_name[0].upper()}{m_name[1:]}")

        if m_desc:
            out.append(f"    /** {m_desc} */")

        override_str = ""
        if m_name == "close" and closeable:
            override_str = "override "
            has_custom_close_method = True
        elif m_name in ("toString", "equals", "hashCode"):
            override_str = "override "

        ret_declaration = f": {ret_kt}" if ret_kt != "Unit" else ""
        out.append(f"    {override_str}fun {m_name}({', '.join(arg_list)}){ret_declaration} {{")
        out.append("        checkClosed()")
        if ret_kt == "Unit":
            out.append(f"        {jni_fn}({', '.join(jni_arg_list)})")
        else:
            out.append(f"        val res = {jni_fn}({', '.join(jni_arg_list)})")
            if handle_cls or ret_kt.endswith("Gen"):
                target_cls = ret_kt
                out.append(f"        return {target_cls}(res)")
            else:
                out.append("        return res")
        out.append("    }\n")

    if closeable and not has_custom_close_method:
        out.append("    override fun close() {")
        out.append("        if (isClosed.compareAndSet(false, true)) {")
        out.append("            nativeClose(handle)")
        out.append("        }")
        out.append("    }\n")

    out.append("    private fun checkClosed() {")
    out.append(f'        if (isClosed.get()) throw IllegalStateException("{cls_name} is closed")')
    out.append("    }\n")

    # Native external declarations
    out.append("    // --- Native External Declarations ---")
    for m in methods:
        m_name = m.get("name")
        jni_fn = m.get("jni_name", f"native{m_name[0].upper()}{m_name[1:]}")
        ret_info = m.get("return") or m.get("returns") or {}
        ret_type_raw = ret_info.get("type", "Void") if isinstance(ret_info, dict) else "Void"
        ret_kt = map_type_to_kotlin(ret_type_raw)
        handle_cls = ret_info.get("handle_class") if isinstance(ret_info, dict) else None

        if handle_cls or ret_kt in ("Document", "Element", "Elements", "Pattern", "Matcher", "MatchResult", "Runtime", "Context", "JSValue", "Module", "Promise", "LuauVM"):
            ret_kt = "Long"

        args = m.get("args", []) or m.get("parameters", []) or []
        ext_args = ["handle: Long"]
        for a in args:
            a_name = a.get("name")
            raw_a_type = a.get("type", "String")
            a_kt_type = map_type_to_kotlin(raw_a_type)
            if a_kt_type in ("Document", "Element", "Elements", "Pattern", "Matcher", "MatchResult", "Runtime", "Context", "JSValue", "Module", "Promise", "LuauVM"):
                ext_args.append(f"{a_name}: Long")
            elif a_kt_type == "KotlinModule":
                ext_args.append(f"{a_name}: Any")
            else:
                ext_args.append(f"{a_name}: {a_kt_type}")

        ret_decl = f": {ret_kt}" if ret_kt != "Unit" else ""
        out.append(f"    private external fun {jni_fn}({', '.join(ext_args)}){ret_decl}")

    if closeable and not has_custom_close_method:
        out.append("    private external fun nativeClose(handle: Long)")

    out.append("}\n")
    return "\n".join(out)

def generate_luau_binding(spec):
    cls_name = spec.get("class")
    package = spec.get("package", "io.github.luandro")
    module = package.split(".")[-1]
    methods = spec.get("methods", []) or []
    luau_info = spec.get("luau_mapping", {}) or {}

    mod_name = luau_info.get("module_name", module)
    mt_name = luau_info.get("metatable", f"luandro.{module}.{cls_name}")

    out = [AUTO_GEN_HEADER]
    out.append("#include <lua.h>")
    out.append("#include <lualib.h>")
    out.append('#include "binding/luau/luau_binding.h"\n')
    out.append(f"namespace nrp::luau::{module} {{\n")

    # Method function wrappers
    method_regs = []
    for m in methods:
        m_name = m.get("name")
        luau_func = m.get("luau_name", m_name)
        if not luau_func:
            continue
        c_func = f"lua_{cls_name.lower()}_{m_name}"
        method_regs.append((luau_func, c_func))

        out.append(f"static int {c_func}(lua_State* L) {{")
        out.append(f'    return with_lua_exceptions(L, "{cls_name}:{m_name}", [&]() -> int {{')
        out.append(f'        Handle h = check_handle_userdata(L, 1, "{mt_name}");')
        out.append("        (void)h;")
        out.append("        return 0;")
        out.append("    });")
        out.append("}\n")

    # Module open function
    out.append(f"inline void register_{cls_name.lower()}_binding(lua_State* L) {{")
    out.append(f"    static const luaL_Reg funcs[] = {{")
    for luau_func, c_func in method_regs:
        out.append(f'        {{"{luau_func}", {c_func}}},')
    out.append("        {nullptr, nullptr}")
    out.append("    };\n")
    out.append(f'    register_metatable(L, "{mt_name}", nullptr, funcs);')
    out.append("}\n")

    out.append(f"}} // namespace nrp::luau::{module}\n")
    return "\n".join(out)

def generate_markdown_doc(spec):
    cls_name = spec.get("class")
    package = spec.get("package", "")
    desc = spec.get("description", "").strip()
    lifecycle = spec.get("lifecycle", {}) or {}
    thread_safety = spec.get("thread_safety", "not_thread_safe")
    methods = spec.get("methods", []) or []
    examples = spec.get("examples", {}) or {}

    out = [AUTO_GEN_DOC_HEADER]
    out.append(f"# `{cls_name}` API Reference\n")
    out.append(f"**Package:** `{package}`  ")
    out.append(f"**Thread Safety:** `{thread_safety}`  ")
    if isinstance(lifecycle, dict) and lifecycle.get("created_by"):
        out.append(f"**Created By:** `{lifecycle.get('created_by')}`  ")
        out.append(f"**Destroyed By:** `{lifecycle.get('destroyed_by')}`  \n")

    out.append("## Overview\n")
    out.append(desc + "\n")

    out.append("## Methods Summary\n")
    out.append("| Method | Return Type | Description |")
    out.append("|--------|-------------|-------------|")

    for m in methods:
        m_name = m.get("name")
        m_desc = m.get("description", "").replace("\n", " ").strip()
        ret_info = m.get("return", {})
        ret_type = ret_info.get("type", "Void") if isinstance(ret_info, dict) else "Void"
        out.append(f"| `{m_name}()` | `{ret_type}` | {m_desc} |")

    out.append("\n## Method Details\n")
    for m in methods:
        m_name = m.get("name")
        m_desc = m.get("description", "").strip()
        ret_info = m.get("return", {})
        ret_type = ret_info.get("type", "Void") if isinstance(ret_info, dict) else "Void"
        args = m.get("args", []) or m.get("parameters", []) or []

        out.append(f"### `{m_name}`\n")
        out.append(m_desc + "\n")
        if args:
            out.append("**Arguments:**\n")
            for a in args:
                out.append(f"- `{a.get('name')}` (`{a.get('type')}`): {a.get('description', '')}")
            out.append("")
        out.append(f"**Returns:** `{ret_type}`\n")

    if isinstance(examples, dict) and examples:
        out.append("## Examples\n")
        for lang, code in examples.items():
            out.append(f"```{lang}\n{code}\n```\n")

    return "\n".join(out)

def process_spec_file(filepath):
    print(f"  Processing spec: {filepath.relative_to(SPEC_DIR)}")
    with open(filepath, "r", encoding="utf-8") as f:
        spec = yaml.safe_load(f)

    if not spec or "class" not in spec:
        return

    cls_name = spec["class"]
    package = spec.get("package", "io.github.luandro")
    module = package.split(".")[-1]

    # Output paths
    native_out = OUT_NATIVE / module / f"{cls_name}.gen.h"
    jni_out = OUT_JNI / module / f"{cls_name}_jni.gen.cpp"
    kotlin_pkg_dir = OUT_KOTLIN / package.replace(".", "/")
    kotlin_out = kotlin_pkg_dir / f"{cls_name}Gen.kt"
    luau_out = OUT_LUAU / module / f"{cls_name}_binding.gen.cpp"
    docs_out = OUT_DOCS / module / f"{cls_name}.md"

    # Create directories
    native_out.parent.mkdir(parents=True, exist_ok=True)
    jni_out.parent.mkdir(parents=True, exist_ok=True)
    kotlin_out.parent.mkdir(parents=True, exist_ok=True)
    luau_out.parent.mkdir(parents=True, exist_ok=True)
    docs_out.parent.mkdir(parents=True, exist_ok=True)

    # Write generated files
    with open(native_out, "w", encoding="utf-8") as f:
        f.write(generate_native_header(spec))

    with open(jni_out, "w", encoding="utf-8") as f:
        f.write(generate_jni_impl(spec))

    with open(kotlin_out, "w", encoding="utf-8") as f:
        f.write(generate_kotlin_wrapper(spec))

    with open(luau_out, "w", encoding="utf-8") as f:
        f.write(generate_luau_binding(spec))

    with open(docs_out, "w", encoding="utf-8") as f:
        f.write(generate_markdown_doc(spec))

def main():
    print("==========================================================================")
    print("Luandro NRP — Binding Generator (Phase 10)")
    print("==========================================================================")
    spec_files = glob.glob(str(SPEC_DIR / "**" / "*.yaml"), recursive=True)
    print(f"Found {len(spec_files)} ASL spec files.\n")

    for sf in sorted(spec_files):
        process_spec_file(Path(sf))

    print("\nGeneration completed successfully!")
    print(f"  - Native headers:  {OUT_NATIVE}")
    print(f"  - JNI bindings:    {OUT_JNI}")
    print(f"  - Kotlin wrappers: {OUT_KOTLIN}")
    print(f"  - Luau bindings:   {OUT_LUAU}")
    print(f"  - Markdown docs:   {OUT_DOCS}")

if __name__ == "__main__":
    main()
